SELECT 
    'Green Taxi' as taxi_type,
    VendorID as vendor_id,
    {{ get_vendor_name('VendorID') }} as vendor_name,
    RateCodeID as rate_code_id,
    {{ get_rate_code_name('RateCodeID') }} as rate_code_description,
    PULocationID as pickup_location_id,
    DOLocationID as dropoff_location_id,
    lpep_pickup_datetime as pickup_datetime,
    lpep_dropoff_datetime as dropoff_datetime,
    trip_distance,
    store_and_fwd_flag,
    passenger_count,
    payment_type,
    {{ get_payment_type('payment_type') }} as payment_type_description,
    fare_amount,
    extra,
    mta_tax,
    tip_amount,
    tolls_amount,
    improvement_surcharge,
    congestion_surcharge,
    NULL as airport_fee,
    total_amount

FROM {{source('nyc_taxi_data', 'green_taxi')}}